<a href="https://colab.research.google.com/github/M-mitra-IN/DS-AI-ML-ASD-Assignment/blob/main/Day_3_assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
#1
score = np.array([])
for i in range(0,10):
  sc = int(input("Enter score: "))
  score = np.append(score,sc)
arr = np.co98py(score)
filter = arr[arr>50]
print(filter)

Enter score: 51
Enter score: 50
Enter score: 63
Enter score: 90
Enter score: 91
Enter score: 99
Enter score: 1
Enter score: 45
Enter score: 43
Enter score: 91
[51. 63. 90. 91. 99. 91.]


In [5]:
#2
print("Mean score: ", np.mean(score))

Mean score:  62.4


In [6]:
#3
print("Median score: ", np.median(score))

Median score:  57.0


In [8]:
#4
values, counts = np.unique(score, return_counts=True)
mode = values[np.argmax(counts)]
print("Mode of score: ", mode)

Mode of score:  91.0


In [11]:
Temperature = np.array([
    [23.5, 34.1, 31.2, 22.8, 29.7, 38.0, 36.2],
    [27.4, 25.5, 32.6, 30.9, 39.5, 21.3, 34.7],
    [26.8, 28.1, 35.6, 22.2, 30.4, 33.7, 37.9],
    [24.2, 29.8, 31.0, 27.7, 36.1, 39.0, 28.3]])


In [14]:
#5
temp = np.copy(Temperature)
print(temp)
print("\nTemperatures in week 2:", temp[1])

[[23.5 34.1 31.2 22.8 29.7 38.  36.2]
 [27.4 25.5 32.6 30.9 39.5 21.3 34.7]
 [26.8 28.1 35.6 22.2 30.4 33.7 37.9]
 [24.2 29.8 31.  27.7 36.1 39.  28.3]]

Temperatures in week 2: [27.4 25.5 32.6 30.9 39.5 21.3 34.7]


In [16]:
#6
print("Maximum Temperatures over the month: ", np.max(temp))

Maximum Temperatures over the month:  39.5


In [19]:
#7
tmax = np.max(temp)
tmin = np.min(temp)
normalised_temp = np.round(((temp - tmin)/(tmax - tmin)),3)
print("Normalised Temperature:\n", normalised_temp)

Normalised Temperature:
 [[0.121 0.703 0.544 0.082 0.462 0.918 0.819]
 [0.335 0.231 0.621 0.527 1.    0.    0.736]
 [0.302 0.374 0.786 0.049 0.5   0.681 0.912]
 [0.159 0.467 0.533 0.352 0.813 0.973 0.385]]


In [22]:
#8
print("Standard deviation of temperatures: ", np.round((np.std(temp)),3))

Standard deviation of temperatures:  5.241


In [24]:
stock = np.array([
    [[67, 10, 55, 95, 45],
     [35, 75, 56, 85, 66],
     [30, 11, 23, 84, 86],
     [83, 60, 58, 76, 43]],

    [[70, 26, 17, 41, 94],
     [59, 79, 95, 64, 82],
     [71, 30, 16, 74, 48],
     [92, 47, 82, 64, 10]],

    [[55, 98, 39, 97, 63],
     [12, 71, 39, 76, 79],
     [38, 36, 64, 18, 24],
     [32, 42, 47, 37, 67]]
])

In [25]:
#9
stock_copy = np.copy(stock)
print("Stock of 2nd Product over 3rd Week:\n",stock_copy[1,2,:])

Stock of 2nd Product over 3rd Week:
 [71 30 16 74 48]


In [26]:
#10
print("Total stock of each product over weeks and categories:", np.sum(stock_copy,axis=(1,2)))

Total stock of each product over weeks and categories: [1143 1161 1034]


In [27]:
ratings = np.array([
    8, 6, 7, 9, 5, 4, 10, 7, 6, 3,
    9, 8, 7, 5, 6, 10, 8, 4, 9, 7,
    6, 8, 5, 7, 3, 6, 10, 9, 8, 2,
    1, 4, 5, 6, 7, 8, 9, 10, 4, 6,
    8, 7, 3, 5, 6, 9, 10, 7, 8, 6
])

In [29]:
#11
r = np.copy(ratings)
print("Number of people who rated above 7: " ,np.sum(r>7))

Number of people who rated above 7:  19


In [30]:
#12
print("Number of people who rated neutral(5): " ,np.sum(r==7))

Number of people who rated neutral(5):  8


In [32]:
#13
rmax = np.max(r)
rmin = np.min(r)
normalised_rating = np.round(((r - rmin)/(rmax - rmin)),2)
print("Normalised Temperature:\n", normalised_rating)

Normalised Temperature:
 [0.78 0.56 0.67 0.89 0.44 0.33 1.   0.67 0.56 0.22 0.89 0.78 0.67 0.44
 0.56 1.   0.78 0.33 0.89 0.67 0.56 0.78 0.44 0.67 0.22 0.56 1.   0.89
 0.78 0.11 0.   0.33 0.44 0.56 0.67 0.78 0.89 1.   0.33 0.56 0.78 0.67
 0.22 0.44 0.56 0.89 1.   0.67 0.78 0.56]


In [33]:
steps = np.array([
    [5234, 6342, 7001, 8450, 9100, 7200, 6540],
    [4320, 4890, 5100, 6001, 6790, 7300, 6900],
    [10200, 9800, 11000, 11500, 9000, 8700, 9500],
    [3000, 3500, 4000, 4200, 3900, 3700, 4500],
    [8120, 7890, 8050, 8700, 9200, 8800, 9400]])

In [36]:
#14
steps_copy = np.copy(steps)
avg = np.average(steps_copy,axis=1)
print("Average steps per user: ", np.round(avg,0))

Average steps per user:  [7124. 5900. 9957. 3829. 8594.]


In [38]:
#15
print("Steps for each user on day 3: ", steps_copy[:,2])

Steps for each user on day 3:  [ 7001  5100 11000  4000  8050]


In [39]:
#16
print("Users who walked more than 7000 steps on any day:")

for i in range(steps_copy.shape[0]):
    if np.any(steps_copy[i] > 7000):
        print("User", i + 1)

Users who walked more than 7000 steps on any day:
User 1
User 2
User 3
User 5


In [41]:
trial_results = np.array([
    [10.2, 10.5, 10.1, 10.4, 10.3, 10.6, 10.0, 10.2, 10.5, 10.3],  # Sample 1
    [15.0, 15.5, 14.9, 15.2, 15.3, 15.1, 14.8, 15.4, 15.0, 15.2],  # Sample 2
    [20.1, 19.8, 20.0, 20.5, 20.2, 20.3, 20.6, 20.4, 19.9, 20.1]   # Sample 3
])


In [43]:
#17
tr = np.copy(trial_results)
print("Mean result of each sample: ", np.mean(tr,axis=1))

Mean result of each sample:  [10.31 15.14 20.19]


In [50]:
#18
trial = np.array([])
for i in range(tr.shape[0]):
    deviations = np.abs(tr[i] - np.mean(tr[i]))
    trial = np.append(trial, (np.argmax(deviations)))
print("Trials for each sample that had highest deviation from mean: ", trial)
print("NOTE: Trial count starts from 0")

Trials for each sample that had highest deviation from mean:  [6. 1. 6.]
NOTE: Trial count starts from 0


In [51]:
vitals = np.array([
    [  # Patient 1
        [98.6, 72, 18], [98.7, 75, 19], [99.0, 70, 20], [98.4, 73, 18], [98.5, 74, 19]
    ],
    [  # Patient 2
        [99.1, 80, 20], [99.3, 78, 22], [98.9, 82, 21], [99.0, 79, 20], [99.2, 81, 21]
    ]
])

In [52]:
#19
vitals_copy = np.copy(vitals)
print("Vitals for Patient 1 on Day 4:", vitals_copy[0, 3])

Vitals for Patient 1 on Day 4: [98.4 73.  18. ]


In [54]:
#20
vital = vitals_copy[1, :, 2]
vals, counts = np.unique(vital, return_counts=True)
mode = vals[np.argmax(counts)]
print("Patient 2 Vital 3")
print("Selected vital values:", vital)
print("Mode of selected vital sign:", mode)


Patient 2 Vital 3
Selected vital values: [20. 22. 21. 20. 21.]
Mode of selected vital sign: 20.0
